name: Update Flake

on:
  repository_dispatch:
    types: [dependency-updated]
  workflow_dispatch: {}

jobs:
  update:
    runs-on: ubuntu-24.04
    steps:
      - name: Clone repository
        uses: actions/checkout@v5
        with:
          token: "${{ secrets.GITBOT_TOKEN }}"
      
      - name: Install nix
        uses: cachix/install-nix-action@v31
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes
          install_url: https://releases.nixos.org/nix/nix-2.28.0/install
      
      - name: Set up git
        run: |
          git config user.email gitbot@mox-desktop.dev
          git config user.name "Git Bot"
      
      - name: Update flake and commit
        run: |
          PROJECT_NAME="${{ github.event.client_payload.project_name }}"
          
          if [ -z "$PROJECT_NAME" ]; then
            echo "No project name specified, skipping update."
            exit 0
          fi
      
          echo "Updating flake input: $PROJECT_NAME"
          nix flake update "$PROJECT_NAME"
      
          if git diff --quiet flake.lock; then
            echo "No changes to flake.lock"
            exit 0
          fi
      
          git add flake.lock
          git commit -m "flake.lock: Update $PROJECT_NAME $(date '+%Y-%m-%d %H:%M')"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITBOT_TOKEN }}
